books/urls.py
from django.conf.urls import url
from books import views

"""
urls_conf namespace = book

Perhatikan ini:
1. karena sifatnya hierarki dari url utama, coba lihat /crud/urls.py
prefix semua url diawali dengan /books.

2. di template panggil alias lengkap dengan namespace nya.

contoh:
book:list
book:delete
"""
app_name = 'book'

urlpatterns = [
    url(r'^$', views.bookall, name="list"), # list merupakan alias dari url ini
    url(r'^new$', views.booknew, name="new"),
    url(r'^(?P<pk>\d+)$', views.bookdetail, name="detail"),
    url(r'^edit/(?P<pk>\d+)$', views.bookedit, name="edit"),
    url(r'^delete/(?P<pk>\d+)$', views.bookdelete, name="delete"),
]

crud/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from books.views import home

urlpatterns = [
    url(r'^$', home),
    url(r'^admin/', admin.site.urls),
    url(r'^authors/', include('authors.urls')),
    url(r'^books/', include('books.urls')),
    url(r'^bookcases/', include('bookcase.urls')),
]

books/models.py
from __future__ import unicode_literals
import datetime
from django.db import models
from bookcase.models import BookCase
from authors.models import Author

YEAR_CHOICES = [(r, r) for r in range(1984, datetime.date.today().year+1)]


class Books(models.Model):
    book_case = models.ForeignKey(BookCase)
    title = models.CharField(max_length=24)
    authors = models.ManyToManyField(Author)
    sub_topic = models.CharField(max_length=24)
    publisher = models.CharField(max_length=24)
    pages = models.IntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    tags = models.CharField(max_length=24)
    year = models.IntegerField(choices=YEAR_CHOICES, default=datetime.date.today().year)

    class Meta:
        verbose_name_plural = 'book'

    def __unicode__(self):
        return self.title

books/forms.py
from django.forms import ModelForm
from books.models import Books

"""
Setiap ModelForm harus memiliki atribut fields atau exclude
"""


class BookForm(ModelForm):
    class Meta:
        # validation rules diambil dari model Books
        model = Books
        """
        field-field yang di tampilkan
        """
        fields = [
            'book_case',
            'title',
            'authors',
            'sub_topic',
            'publisher',
            'pages',
            'price',
            'tags',
            'year'
        ]
        """
        pengecualian, field yang ada di daftar ini tidak akan ditampilkan
        """
        # exclude = ['fieldname']

books/views.py
from django.shortcuts import render_to_response, redirect, get_object_or_404
from django.template import RequestContext
from books.models import Books
from books.forms import BookForm


def home(request):
    return render_to_response("index.html")


def bookall(request):
    books = Books.objects.all()
    context = {
        'books': books
    }
    return render_to_response('books/bookall.html', context)


def bookdetail(request, pk):
    book = Books.objects.get(pk=pk)
    context = {
        'book': book
    }

    return render_to_response('books/bookdetail.html', context)


def booknew(request):
    # generic 'old' way
    if 'POST' == request.method:
        form = BookForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('book:list')
    else:
        form = BookForm()

    return render_to_response('books/booknew.html', {
        'form': form
    }, context_instance=RequestContext(request))


def bookedit(request, pk):
    book = get_object_or_404(Books, pk=pk)
    # best practice
    form = BookForm(request.POST or None, instance=book)

    if form.is_valid():
        form.save()
        return redirect('book:detail', pk=book.id)
    return render_to_response('books/bookedit.html', {
        'form': form,
        'book': book
    }, context_instance=RequestContext(request))


def bookdelete(request, pk):
    book = Books.objects.get(pk=pk)

    if 'POST' == request.method:
        book.delete()
        return redirect('book:all')

    return render_to_response('books/confirmdelete.html', {'object': book})

templates/books/bookall.html
{% extends 'base.html' %}

{% block content %}
    <h1>Books</h1>
    <ul>
        {% for book in books %}
            <li>
                <a href="{% url "book:detail" book.id %}">{{ book.title }}</a>:
                <a href="{% url "book:edit" book.id %}">Edit</a> |
                <a href="{% url "book:delete" book.id %}" method="post">Delete</a>
            </li>
        {% empty %}
            No Data.
        {% endfor %}
    </ul>

    <a href="/">Home</a> |
    <a href="{% url "book:new" %}">New</a>
{% endblock %}

templates/books/bookdetail.html
{% extends 'base.html' %}

{% block content %}
<h1>Book: {{ book }}</h1>
<table>
	<tr>
		<th>ID</th>
		<td>{{ book.id }}</td>
	</tr>
	<tr>
		<th>Title</th>
		<td>{{ book.title }}</td>
	</tr>
	<tr>
		<th>Authors</th>
		<td>
			{% for author in book.authors.all %}
				<li>{{ author.name }}</li>
			{% endfor %}
		</td>
	</tr>
	<tr>
		<th>Publisher</th>
		<td>{{ book.publisher }}</td>
	</tr>
	<tr>
		<th>Sub Topic</th>
		<td>{{ book.sub_topic }}</td>
	</tr>
	<tr>
		<th>Pages</th>
		<td>{{ book.pages }}</td>
	</tr>
	<tr>
		<th>Price</th>
		<td>${{ book.price }}</td>
	</tr>
	<tr>
		<th>Tags</th>
		<td>{{ book.tags }}</td>
	</tr>
	<tr>
		<th>Year</th>
		<td>{{ book.year }}</td>
	</tr>
</table>
<a href="{% url "book:list"%}">Back</a> |
<a href="{% url "book:edit" book.id %}">Edit</a> |
<a href="{% url "book:delete" book.id %}" method="post">Delete</a>
{% endblock %}

templates/books/bookedit.html
{% extends 'base.html' %}

{% block content %}
<h3>Update Book: {{ book }}</h3>
<form action="" method="post">
    {% csrf_token %}
    {% include "books/form.html" %}
    <input type="submit" value="Submit" />
</form>
<a href="{% url 'book:list' %}">Back</a>
{% endblock %}

templates/books/booknew.html
{% extends 'base.html' %}

{% block content %}
<h3>Create new Book</h3>
<form action="" method="post">
    {% csrf_token %}
    {% include "books/form.html" %}
    <input type="submit" value="Submit" />
</form>
<a href="{% url 'book:list' %}">Back</a>
{% endblock %}

templates/books/confirmdelete.html
<form method="post">{% csrf_token %}
	{# lihat method __unicode__() di class model. #} 
	{# Di Java kita familiar dengan method toString(). #}
    <h3>Are you sure you want to delete "{{ object }}"?</h3>
    <input type="submit" value="Confirm"/>
</form>
<a href="{% url 'book:detail' object.id %}">Back</a>

templates/books/form.html
{% for field in form %}
    <div class="fieldWrapper">
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}
        {% if field.help_text %}
            <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
    </div>
{% endfor %}