authors/urls.py
from django.conf.urls import url
from authors import views

"""
urls_conf namespace = author

Perhatikan ini:
1. karena sifatnya hierarki dari url utama, coba lihat /crud/urls.py
prefix semua url diawali dengan /authors.

2. di template panggil alias lengkap dengan namespace nya.

contoh:
author:list
author:delete
"""
app_name = 'author'

urlpatterns = [
    url(r'^$', views.authorall, name="list"), # list merupakan alias dari url ini
    url(r'^new$', views.authornew, name="new"),
    url(r'^(?P<pk>\d+)$', views.authordetail, name="detail"),
    url(r'^edit/(?P<pk>\d+)$', views.authoredit, name="edit"),
    url(r'^delete/(?P<pk>\d+)$', views.authordelete, name="delete"),
]

crud/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from books.views import home

urlpatterns = [
    url(r'^$', home),
    url(r'^admin/', admin.site.urls),
    url(r'^authors/', include('authors.urls')),
    url(r'^books/', include('books.urls')),
    url(r'^bookcases/', include('bookcase.urls')),
]

authors/models.py
from __future__ import unicode_literals

from django.db import models


class Author(models.Model):
    name = models.CharField(max_length=100)
    age = models.IntegerField()

    class Meta:
        verbose_name_plural = 'author'

    def __unicode__(self):
        return self.name

authors/forms.py
from django.forms import ModelForm
from authors.models import Author

"""
Setiap ModelForm harus memiliki atribut fields atau exclude
"""


class AuthorForm(ModelForm):
    class Meta:
        # validation rules diambil dari model Author
        model = Author
        """
        field-field yang di tampilkan
        """
        fields = [
            'name',
            'age',
        ]
        """
        pengecualian, field yang ada di daftar ini tidak akan ditampilkan
        """
        # exclude = ['fieldname']

authors/views.py
from django.shortcuts import render_to_response, redirect, get_object_or_404
from django.template import RequestContext
from authors.models import Author
from authors.forms import AuthorForm


def authorall(request):
    authors = Author.objects.all()
    return render_to_response("authors/authorall.html", {'authors': authors})


def authordetail(request, pk):
    author = get_object_or_404(Author, pk=pk)
    return render_to_response("authors/authordetail.html", {'author': author})


def authornew(request):
    form = AuthorForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('author:list')

    return render_to_response("authors/authornew.html", {
        'form': form
    }, context_instance=RequestContext(request))


def authoredit(request, pk):
    author = get_object_or_404(Author, pk=pk)
    form = AuthorForm(request.POST or None, instance=author)

    if form.is_valid():
        form.save()
        return redirect("author:detail", pk=author.id)
    return render_to_response("authors/authoredit.html", {
        'author': author,
        'form': form
    }, context_instance=RequestContext(request))


def authordelete(request, pk):
    author = Author.objects.get(pk=pk)

    if 'POST' == request.method:
        author.delete()
        return redirect('author:all')

    return render_to_response('authors/confirmdelete.html', {'object': author})

templates/authors/authorall.html
{% extends 'base.html' %}

{% block content %}
	<h1>Authors</h1>
	<ul>
		{% for author in authors %}
			<li>
				<a href="{% url 'author:detail' author.id %}">{{ author.name }}</a>: 
				<a href="{% url 'author:edit' author.id %}">Edit</a> | 
				<a href="{% url 'author:delete' author.id %}">Delete</a>
			</li>
        {% empty %}
            No Data.
		{% endfor %}
	</ul>

	<a href="/">Home</a> |
	<a href="{% url "author:new" %}">New</a>
{% endblock %}

templates/authors/authordetail.html
{% extends 'base.html' %}

{% block content %}
<h1>Author: {{ author }}</h1>
<table>
	<tr>
		<th>Name</th>
		<td>{{ author.name }}</td>
	</tr>
	<tr>
		<th>Age</th>
		<td>{{ author.age }}</td>
	</tr>
</table>
<a href="{% url 'author:list' %}">Back</a> | 
<a href="{% url 'author:edit' author.id %}">Edit</a> | 
<a href="{% url 'author:delete' author.id %}">Delete</a>
{% endblock %}

templates/authors/authoredit.html
{% extends 'base.html' %}

{% block content %}
<h3>Edit Author: {{ author }}</h3>
<form action="" method="post">
    {% csrf_token %}
    {% include "authors/form.html" %}
    <input type="submit" value="Submit" />
</form>
<a href="{% url 'author:list' %}">Back</a>
{% endblock %}

templates/authors/authornew.html
{% extends 'base.html' %}

{% block content %}
<h3>Create new Author</h3>
<form action="" method="post">
    {% csrf_token %}
    {% include "authors/form.html" %}
    <input type="submit" value="Submit" />
</form>
<a href="{% url 'author:list' %}">Back</a>
{% endblock %}

templates/authors/confirmdelete.html
<form method="post">{% csrf_token %}
	{# lihat method __unicode__() di class model. #} 
	{# Di Java kita familiar dengan method toString(). #}
    <h3>Are you sure you want to delete "{{ object }}"?</h3>
    <input type="submit" value="Confirm"/>
</form>
<a href="{% url 'author:detail' object.id %}">Back</a>

templates/authors/form.html
{% for field in form %}
    <div class="fieldWrapper">
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}
        {% if field.help_text %}
            <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
    </div>
{% endfor %}