bookcase/urls.py
from django.conf.urls import url
from bookcase import views

"""
urls_conf namespace = bookcase

Perhatikan ini:
1. karena sifatnya hierarki dari url utama, coba lihat /crud/urls.py
prefix semua url diawali dengan /bookcase.

2. di template panggil alias lengkap dengan namespace nya.

contoh:
bookcase:list
bookcase:delete
"""
app_name = 'bookcase'

urlpatterns = [
    url(r'^$', views.bookcaseall, name="list"), # list merupakan alias dari url ini
    url(r'^new$', views.bookcasenew, name="new"),
    url(r'^(?P<pk>\d+)$', views.bookcasesdetail, name="detail"),
    url(r'^edit/(?P<pk>\d+)$', views.bookcaseedit, name="edit"),
    url(r'^delete/(?P<pk>\d+)$', views.bookcasedelete, name="delete"),
]

crud/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from books.views import home

urlpatterns = [
    url(r'^$', home),
    url(r'^admin/', admin.site.urls),
    url(r'^authors/', include('authors.urls')),
    url(r'^books/', include('books.urls')),
    url(r'^bookcases/', include('bookcase.urls')),
]

books/models.py
from __future__ import unicode_literals
import datetime
from django.db import models
from bookcase.models import BookCase
from authors.models import Author

YEAR_CHOICES = [(r, r) for r in range(1984, datetime.date.today().year+1)]


class Books(models.Model):
    book_case = models.ForeignKey(BookCase)
    title = models.CharField(max_length=24)
    authors = models.ManyToManyField(Author)
    sub_topic = models.CharField(max_length=24)
    publisher = models.CharField(max_length=24)
    pages = models.IntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    tags = models.CharField(max_length=24)
    year = models.IntegerField(choices=YEAR_CHOICES, default=datetime.date.today().year)

    class Meta:
        verbose_name_plural = 'book'

    def __unicode__(self):
        return self.title

templates/bookcases/bookcaseall.html
{%  extends 'base.html' %}

{%  block content %}
<h1>Book Cases</h1>
    <ul>
    {% for bookcase in bookcases %}
        <li>
            <a href="{% url 'bookcase:detail' bookcase.id %}">{{ bookcase.get_book_case_display }}</a>:
            <a href="{% url 'bookcase:edit' bookcase.id %}">Edit</a> |
            <a href="{% url 'bookcase:delete' bookcase.id %}">Delete</a>
        </li>
    {% empty %}
            No Data.
    {% endfor %}
    </ul>
    <a href="/">Home</a> |
    <a href="{% url 'bookcase:new' %}">New</a>
{% endblock %}

templates/bookcases/bookcasedetail.html
{% extends 'base.html' %}

{% block content %}
<h1>Book Case: {{ bookcase }}</h1>
    <table>
    <tr>
        <th>ID</th>
        <td>{{ bookcase.id }}</td>
    </tr>
    <tr>
        <th>Name</th>
        <td>{{ bookcase.get_book_case_display }}</td>
    </tr>
    </table>
    <a href="{% url 'bookcase:list' %}">Back</a> |
    <a href="{% url 'bookcase:edit' bookcase.id %}">Edit</a> |
    <a href="{% url 'bookcase:delete' bookcase.id %}">Delete</a>
{% endblock %}

templates/bookcases/bookcaseedit.html
{% extends 'base.html' %}

{% block content %}
<h3>Edit Book Case: {{ bookcase }}</h3>
<form action="" method="post">
    {% csrf_token %}
    <p>ID: {{ bookcase.id }}</p>
    {% include "bookcases/form.html" %}
    <input type="submit" value="Submit" />
</form>
<a href="{% url 'bookcase:detail' bookcase.id %}">Back</a>
{% endblock %}

templates/bookcases/bookcasenew.html
{% extends 'base.html' %}

{% block content %}
<h3>Create new Book Case</h3>
<form action="" method="post">
    {% csrf_token %}
    {% include "bookcases/form.html" %}
    <input type="submit" value="Submit" />
</form>
<a href="{% url 'bookcase:list' %}">Back</a>
{% endblock %}

templates/bookcases/confirmdelete.html
<form method="post">{% csrf_token %}
	{# lihat method __unicode__() di class model. #}
	{# Di Java kita familiar dengan method toString(). #}
    <h3>Are you sure you want to delete "{{ object }}"?</h3>
    <input type="submit" value="Confirm"/>
</form>
<a href="{% url 'bookcase:detail' object.id %}">Back</a>

templates/bookcases/form.html
{% for field in form %}
    <div class="fieldWrapper">
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}
        {% if field.help_text %}
            <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
    </div>
{% endfor %}