bookcase/urls.py
from django.conf.urls import url
from bookcase import views

"""
urls_conf namespace = bookcase

Perhatikan ini:
1. karena sifatnya hierarki dari url utama, coba lihat /crud/urls.py
prefix semua url diawali dengan /bookcase.

2. di template panggil alias lengkap dengan namespace nya.

contoh:
bookcase:list
bookcase:delete
"""
app_name = 'bookcase'

urlpatterns = [
    url(r'^$', views.bookcaseall, name="list"), # list merupakan alias dari url ini
    url(r'^new$', views.bookcasenew, name="new"),
    url(r'^(?P<pk>\d+)$', views.bookcasesdetail, name="detail"),
    url(r'^edit/(?P<pk>\d+)$', views.bookcaseedit, name="edit"),
    url(r'^delete/(?P<pk>\d+)$', views.bookcasedelete, name="delete"),
]

crud/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from books.views import home

urlpatterns = [
    url(r'^$', home),
    url(r'^admin/', admin.site.urls),
    url(r'^authors/', include('authors.urls')),
    url(r'^books/', include('books.urls')),
    url(r'^bookcases/', include('bookcase.urls')),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block page-title %}Crud{% endblock %}</title>
</head>
<body>
{% block content %}

{% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>CRUD Apps</h1>
    <ul>
        <li>
            <a href="{% url 'bookcase:list' %}">Book Cases</a>
        </li>
        <li>
            <a href="{% url 'author:list' %}">Authors</a>
        </li>
        <li>
            <a href="{% url 'book:list' %}">Books</a>
        </li>
    </ul>
{% endblock %}